project_id = "gta-solutions-agentic-dsta"
region = "us-central1"
resource_prefix = "test-v1"
allow_unauthenticated = true
firestore_database_type = "FIRESTORE_NATIVE"
apihub_instance_id = ""
sa_session_init_scheduler_job_schedule = "0 10 * * *"
sa_run_sse_scheduler_job_schedule = "5 10 * * *"
additional_secrets = []
account_email = "test-v1-deployer@gta-solutions-agentic-dsta.iam.gserviceaccount.com"
image_url = "us-central1-docker.pkg.dev/gta-solutions-agentic-dsta/test-v1-repo/test-v1-image:latest"
